name: Build Typst document
on: 
  # push:
  #   paths: "**/*.typ"
  workflow_dispatch:
    inputs:
      directory:
        description: "ディレクトリ"
        required: true
        type: choice
        options:
          - "Semantics with Applications"
      name:
        description: "名前"
        required: false
        default: "main"
        type: string

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_typst_documents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        # with:
        #   fetch-depth: 2

      - name: Install Japanese Fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk

      - name: Setup Typst
        uses: typst-community/setup-typst@v5

      - name: Compile Typst
        run: |
          typst compile \
          --root . \
          "${{ inputs.directory }}/${{ inputs.name }}.typ" \
          "${{ inputs.directory }}_note.pdf"
        # "${{ inputs.directory }}/${{ inputs.name }}.pdf"
        
      - name: Upload to Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          filename: "${{ inputs.directory }}_note.pdf"
          folderId: ${{ secrets.GDRIVE_FOLDER_ID }}
          overwrite: "true"
          userEmail: "shunsukeika@gmail.com"
