name: Build Typst document
on: 
  # push:
  #   paths: "**/*.typ"
  workflow_dispatch:
    inputs:
      directory:
        description: "ディレクトリ"
        required: true
        type: choice
        options:
          - "Semantics with Applications"
      name:
        description: "名前"
        required: false
        default: "main"
        type: string

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_typst_documents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        # with:
        #   fetch-depth: 2

      - name: Install Japanese Fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk

      - name: Setup Typst
        uses: typst-community/setup-typst@v5

      - name: Compile Typst
        run: |
          typst compile \
          --root . \
          "${{ inputs.directory }}/${{ inputs.name }}.typ" \
          "${{ inputs.directory }}_note.pdf"
        # "${{ inputs.directory }}/${{ inputs.name }}.pdf"
        
      - name: Upload to Google Drive
        run: |
          sudo apt-get update && sudo apt-get install -y rclone
          
          cat <<EOF > rclone.conf
          [mydrive]
          type = drive
          client_id = ${{ secrets.GDRIVE_CLIENT_ID }}
          client_secret = ${{ secrets.GDRIVE_CLIENT_SECRET }}
          scope = drive.file
          token = {"access_token":"dummy","token_type":"Bearer","refresh_token":"${{ secrets.GDRIVE_REFRESH_TOKEN }}","expiry":"2000-01-01T00:00:00Z"}
          # ここで保存先フォルダのIDをルートとして固定します
          root_folder_id = ${{ secrets.GDRIVE_FOLDER_ID }}
          EOF

          # root_folder_id を指定したため、宛先は "mydrive:" だけで
          # 自動的にそのフォルダ内を指すようになります
          rclone --config rclone.conf copyto \
            "${{ inputs.directory }}_note.pdf" \
            "mydrive:${{ inputs.directory }}_note.pdf"
